require('settings')
require('keymap')
require('plugins')
require('automatition')

require('plugins.treesitter')
require('plugins.lsp')
require('plugins.theme')
require('plugins.showNotify')
require('plugins.codewindow')
require('plugins.lsp-colors')

require('plugins.nvim-tree')
--require('plugins.neo-tree')
require('plugins.bufferline')
require('plugins.ranger')
require('plugins.bookmarks')
require('plugins.cmdline')
require('plugins.whichkey')
require('plugins.minisurround')
require('plugins.todocomment')
require('plugins.colorizer')
--require('plugins.persistence')

require('plugins.nerd-comment')
require('plugins.neoscroll')
require('plugins.indent-blankline')
require('plugins.snippets')
require('plugins.utilsnips-conf')

require('plugins.emmet')
--require('plugins.vim-airline')
require('plugins.lualine')
require('plugins.vim-dadbod-ui')
require('plugins.git-signs')
require('plugins.floaterm')
