require('settings')
require('keymap')
require('plugins')
require('automatition')

require('plugins.treesitter')
require('plugins.lsp')
require('plugins.theme')

require('plugins.nerdtree')
require('plugins.ranger')
require('plugins.bookmarks')
require('plugins.comment')
require('plugins.neoscroll')
require('plugins.indent-blankline')
require('plugins.utilsnips-conf')
require('plugins.emmet')
require('plugins.vim-airline')
require('plugins.vim-dadbod-ui')
require('plugins.floaterm')
